scripts: fix migrate-and-dump-seeds

diff --git a/scripts/migrate-and-dump-seeds b/scripts/migrate-and-dump-seeds
--- a/scripts/migrate-and-dump-seeds
+++ b/scripts/migrate-and-dump-seeds
@@ -7,7 +7,9 @@ export DATABASE_URL="postgresql://localhost:5432/$DATABASE_NAME?min-pool-size=1&
 export FILE=db/structure_and_seeds.pgbin
 GITREF=${GITREF:-origin/master}
 
-set -E; bundle exec rake db:pg:terminate_connections; set -e
+{ pg_restore --version | grep -q '11.' ;} && { echo "Error! This only works with PostgreSQL v10 cli tools"; exit 1 ;}
+
+bundle exec rake db:pg:terminate_connections || true
 psql -c "DROP DATABASE IF EXISTS \"$DATABASE_NAME\";"
 createdb $DATABASE_NAME
 git checkout "${GITREF}" -- $FILE
@@ -15,3 +17,6 @@ bundle exec rake db:pg:structure_and_data:restore
 bundle exec rake db:migrate
 bundle exec rake db:pg:structure_and_data:dump
 ./scripts/dump-seeds
+
+echo 
+echo "OK"
